# Generated by Django 3.2.7 on 2022-02-20 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('word_id', models.AutoField(primary_key=True, serialize=False)),
                ('word', models.CharField(blank=True, max_length=100, null=True)),
                ('definition', models.TextField(blank=True, null=True)),
                ('example_1', models.TextField(blank=True, null=True)),
                ('example_2', models.TextField(blank=True, null=True)),
                ('origination', models.CharField(blank=True, max_length=50, null=True)),
                ('part_of_speech', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'words',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AudioStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sound', models.FileField(upload_to='\\documents')),
            ],
        ),
        migrations.DeleteModel(
            name='Words',
        ),
    ]
