# Generated by Django 3.2.7 on 2022-03-12 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0003_score'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='score',
            options={},
        ),
    ]
