# Generated by Django 3.2.7 on 2022-03-27 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0007_correctword'),
    ]

    operations = [
        migrations.AlterField(
            model_name='correctword',
            name='word',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
