# Generated by Django 3.2.7 on 2022-03-27 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0008_alter_correctword_word'),
    ]

    operations = [
        migrations.AddField(
            model_name='correctword',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
