# Generated by Django 3.2.7 on 2022-03-28 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0009_correctword_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='correctword',
            old_name='count',
            new_name='correct',
        ),
        migrations.AddField(
            model_name='correctword',
            name='incorrect',
            field=models.IntegerField(default=0),
        ),
    ]
