# Generated by Django 3.2.7 on 2022-04-18 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValidLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_code', models.CharField(max_length=100)),
            ],
        ),
    ]
